# Generated by Django 5.0.4 on 2024-04-09 08:39

import social_media_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_system", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(
                null=True, upload_to=social_media_system.models.post_image_file_path
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
