# Generated by Django 5.0.4 on 2024-04-10 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_media_system",
            "0004_alter_follow_unique_together_follow_followed_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followed_user",
            new_name="followed",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed")},
        ),
    ]
