# Generated by Django 5.0.4 on 2024-04-10 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_system", "0005_rename_followed_user_follow_followed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followed",
            new_name="followed_user",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed_user")},
        ),
    ]
