# Generated by Django 5.0.4 on 2024-04-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_system", "0006_rename_followed_follow_followed_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
