# Generated by Django 5.0.4 on 2024-04-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_system", "0007_alter_follow_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followed_user",
            new_name="following",
        ),
    ]
