# Generated by Django 5.0.4 on 2024-04-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_user_bio_user_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="username"
            ),
        ),
    ]
